-- 07_create_powerbi_mart.sql
-- Project: Actuarial Motor Insurance Risk Analysis
-- Purpose:
--   Create dashboard-friendly mart tables for Power BI.
--
-- Notes:
--   These tables are intentionally denormalized and presentation-oriented.
--   They are built from warehouse tables, analytics views, and generated CSV outputs.

CREATE SCHEMA IF NOT EXISTS mart;

-- ============================================================
-- 1. Drop existing mart tables so script can be rerun
-- ============================================================

DROP TABLE IF EXISTS mart.mart_dashboard_overview;
DROP TABLE IF EXISTS mart.mart_frequency_by_driver_age;
DROP TABLE IF EXISTS mart.mart_frequency_by_driver_age_band;
DROP TABLE IF EXISTS mart.mart_frequency_by_region;
DROP TABLE IF EXISTS mart.mart_frequency_by_vehicle_brand;
DROP TABLE IF EXISTS mart.mart_frequency_by_vehicle_fuel;
DROP TABLE IF EXISTS mart.mart_bonus_malus;
DROP TABLE IF EXISTS mart.mart_claim_severity_summary;
DROP TABLE IF EXISTS mart.mart_candidate_models;
DROP TABLE IF EXISTS mart.mart_model_parameters;
DROP TABLE IF EXISTS mart.mart_simulation_summary;
DROP TABLE IF EXISTS mart.mart_simulation_percentiles;
DROP TABLE IF EXISTS mart.mart_pricing_scenarios;
DROP TABLE IF EXISTS mart.mart_pricing_scenario_percentiles;
DROP TABLE IF EXISTS mart.mart_pricing_summary;

-- ============================================================
-- 2. Dashboard overview
-- ============================================================

CREATE TABLE mart.mart_dashboard_overview AS
SELECT
    policy_count,
    total_exposure,
    total_claim_count,
    claim_frequency,
    claim_payment_count,
    total_claim_amount,
    average_claim_payment,
    median_claim_payment,
    claim_payment_stddev,
    min_claim_payment,
    max_claim_payment,
    loss_cost_per_exposure AS pure_premium
FROM analytics.vw_portfolio_summary;

-- ============================================================
-- 3. Frequency marts
-- ============================================================

CREATE TABLE mart.mart_frequency_by_driver_age AS
SELECT
    driver_age,
    policy_count,
    exposure,
    claim_count,
    claim_frequency
FROM analytics.vw_driver_age_summary
ORDER BY driver_age;

CREATE TABLE mart.mart_frequency_by_driver_age_band AS
SELECT
    driver_age_band,
    policy_count,
    exposure,
    claim_count,
    claim_frequency,
    CASE driver_age_band
        WHEN '18-24' THEN 1
        WHEN '25-34' THEN 2
        WHEN '35-44' THEN 3
        WHEN '45-54' THEN 4
        WHEN '55-64' THEN 5
        WHEN '65-74' THEN 6
        ELSE 7
    END AS sort_order
FROM analytics.vw_driver_age_band_summary
ORDER BY sort_order;

CREATE TABLE mart.mart_frequency_by_region AS
SELECT
    region_code,
    area_code,
    policy_count,
    exposure,
    claim_count,
    claim_frequency,
    claim_payment_count,
    total_claim_amount,
    average_claim_payment,
    median_claim_payment,
    loss_cost_per_exposure
FROM analytics.vw_region_summary
ORDER BY claim_frequency DESC;

CREATE TABLE mart.mart_frequency_by_vehicle_brand AS
SELECT
    vehicle_brand,
    policy_count,
    exposure,
    claim_count,
    claim_frequency
FROM analytics.vw_vehicle_brand_summary
ORDER BY claim_frequency DESC;

CREATE TABLE mart.mart_frequency_by_vehicle_fuel AS
SELECT
    vehicle_gas,
    policy_count,
    exposure,
    claim_count,
    claim_frequency
FROM analytics.vw_vehicle_fuel_summary
ORDER BY claim_frequency DESC;

CREATE TABLE mart.mart_bonus_malus AS
SELECT
    bonus_malus,
    policy_count,
    exposure,
    claim_count,
    claim_frequency
FROM analytics.vw_bonus_malus_summary
ORDER BY bonus_malus;

-- ============================================================
-- 4. Severity marts
-- ============================================================

CREATE TABLE mart.mart_claim_severity_summary AS
SELECT *
FROM analytics.vw_claim_severity_summary;

-- Candidate model artifacts generated by Python
CREATE TABLE mart.mart_candidate_models AS
SELECT *
FROM read_csv_auto(
    'models/candidate_models.csv',
    HEADER = TRUE
);

-- Long-form model parameter table for Power BI validation page
CREATE TABLE mart.mart_model_parameters AS
WITH raw_parameters AS (
    SELECT
        distribution,
        param_1_name AS parameter_code,
        param_1_value AS estimate
    FROM mart.mart_candidate_models

    UNION ALL

    SELECT
        distribution,
        param_2_name AS parameter_code,
        param_2_value AS estimate
    FROM mart.mart_candidate_models
)
SELECT
    distribution,
    parameter_code,
    CASE
        WHEN parameter_code = 'shape_alpha' THEN 'Shape (α)'
        WHEN parameter_code = 'scale_theta' THEN 'Scale (θ)'
        WHEN parameter_code = 'mu' THEN 'μ'
        WHEN parameter_code = 'sigma' THEN 'σ'
        ELSE parameter_code
    END AS parameter,
    estimate,
    CASE
        WHEN distribution = 'Gamma' AND parameter_code = 'shape_alpha' THEN 1
        WHEN distribution = 'Gamma' AND parameter_code = 'scale_theta' THEN 2
        WHEN distribution = 'Lognormal' AND parameter_code = 'mu' THEN 1
        WHEN distribution = 'Lognormal' AND parameter_code = 'sigma' THEN 2
        ELSE 99
    END AS parameter_sort_order
FROM raw_parameters
ORDER BY distribution, parameter_sort_order;

-- ============================================================
-- 5. Monte Carlo pricing simulation marts
-- ============================================================

CREATE TABLE mart.mart_simulation_summary AS
SELECT *
FROM read_csv_auto(
    'outputs/tables/simulation_summary.csv',
    HEADER = TRUE
);

CREATE TABLE mart.mart_simulation_percentiles AS
SELECT *
FROM read_csv_auto(
    'outputs/tables/simulation_percentiles.csv',
    HEADER = TRUE
);

-- ============================================================
-- 6. Scenario pricing marts
-- ============================================================

CREATE TABLE mart.mart_pricing_scenarios AS
SELECT *
FROM read_csv_auto(
    'outputs/tables/pricing_scenario_summary.csv',
    HEADER = TRUE
);

-- One-row executive pricing summary for Power BI KPI cards
CREATE TABLE mart.mart_pricing_summary AS
WITH scenario_values AS (
    SELECT
        MAX(CASE WHEN scenario_name = 'Base Case' THEN expected_loss END) AS base_scenario_premium,
        MAX(CASE WHEN scenario_name = 'Stress Scenario' THEN expected_loss END) AS stress_scenario_premium,
        MAX(CASE WHEN scenario_name = 'Stress Scenario' THEN expected_loss_pct_change_from_base END) AS stress_premium_change_pct
    FROM mart.mart_pricing_scenarios
),
selected_model AS (
    SELECT
        distribution AS selected_severity_model
    FROM mart.mart_candidate_models
    WHERE best_fit = '✓'
)
SELECT
    selected_model.selected_severity_model,
    scenario_values.base_scenario_premium,
    scenario_values.stress_scenario_premium,
    scenario_values.stress_premium_change_pct
FROM scenario_values
CROSS JOIN selected_model;

CREATE TABLE mart.mart_pricing_scenario_percentiles AS
SELECT *
FROM read_csv_auto(
    'outputs/tables/pricing_scenario_percentiles.csv',
    HEADER = TRUE
);

-- ============================================================
-- 7. Mart validation
-- ============================================================

SELECT
    table_schema,
    table_name
FROM information_schema.tables
WHERE table_schema = 'mart'
ORDER BY table_name;

SELECT 'mart_dashboard_overview' AS table_name, COUNT(*) AS row_count FROM mart.mart_dashboard_overview
UNION ALL
SELECT 'mart_frequency_by_driver_age', COUNT(*) FROM mart.mart_frequency_by_driver_age
UNION ALL
SELECT 'mart_frequency_by_driver_age_band', COUNT(*) FROM mart.mart_frequency_by_driver_age_band
UNION ALL
SELECT 'mart_frequency_by_region', COUNT(*) FROM mart.mart_frequency_by_region
UNION ALL
SELECT 'mart_frequency_by_vehicle_brand', COUNT(*) FROM mart.mart_frequency_by_vehicle_brand
UNION ALL
SELECT 'mart_frequency_by_vehicle_fuel', COUNT(*) FROM mart.mart_frequency_by_vehicle_fuel
UNION ALL
SELECT 'mart_bonus_malus', COUNT(*) FROM mart.mart_bonus_malus
UNION ALL
SELECT 'mart_claim_severity_summary', COUNT(*) FROM mart.mart_claim_severity_summary
UNION ALL
SELECT 'mart_candidate_models', COUNT(*) FROM mart.mart_candidate_models
UNION ALL
SELECT 'mart_model_parameters', COUNT(*) FROM mart.mart_model_parameters
UNION ALL
SELECT 'mart_simulation_summary', COUNT(*) FROM mart.mart_simulation_summary
UNION ALL
SELECT 'mart_simulation_percentiles', COUNT(*) FROM mart.mart_simulation_percentiles
UNION ALL
SELECT 'mart_pricing_scenarios', COUNT(*) FROM mart.mart_pricing_scenarios
UNION ALL
SELECT 'mart_pricing_scenario_percentiles', COUNT(*) FROM mart.mart_pricing_scenario_percentiles
UNION ALL
SELECT 'mart_pricing_summary', COUNT(*) FROM mart.mart_pricing_summary;
